// <auto-generated />
using System;
using BookshelfAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookshelfAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231102174439_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookshelfAPI.Models.Author", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            name = "Hilary Maj"
                        },
                        new
                        {
                            id = 2L,
                            name = "Henryka Kołakowski"
                        },
                        new
                        {
                            id = 3L,
                            name = "Maksym Mucha"
                        },
                        new
                        {
                            id = 4L,
                            name = "Zachary Czajkowski"
                        },
                        new
                        {
                            id = 5L,
                            name = "Anna Mika"
                        },
                        new
                        {
                            id = 6L,
                            name = "Miron Bukowski"
                        },
                        new
                        {
                            id = 7L,
                            name = "Filip Staniszewski"
                        },
                        new
                        {
                            id = 8L,
                            name = "Artur Ostrowski"
                        },
                        new
                        {
                            id = 9L,
                            name = "Galfryd Smoliński"
                        },
                        new
                        {
                            id = 10L,
                            name = "Ilona Murawski"
                        },
                        new
                        {
                            id = 11L,
                            name = "Elżbieta Grzyb"
                        },
                        new
                        {
                            id = 12L,
                            name = "Cezary Piekarski"
                        },
                        new
                        {
                            id = 13L,
                            name = "Patrycy Borowski"
                        },
                        new
                        {
                            id = 14L,
                            name = "Damian Sokół"
                        },
                        new
                        {
                            id = 15L,
                            name = "Gertruda Skiba"
                        },
                        new
                        {
                            id = 16L,
                            name = "Beniamin Kucharczyk"
                        },
                        new
                        {
                            id = 17L,
                            name = "Maksym Kucharczyk"
                        },
                        new
                        {
                            id = 18L,
                            name = "Fryderyk Woźniak"
                        },
                        new
                        {
                            id = 19L,
                            name = "Roksana Gutowski"
                        },
                        new
                        {
                            id = 20L,
                            name = "Tobiasz Włodarczyk"
                        },
                        new
                        {
                            id = 21L,
                            name = "Laurencjusz Gruszczyński"
                        },
                        new
                        {
                            id = 22L,
                            name = "Bazyli Wojtas"
                        },
                        new
                        {
                            id = 23L,
                            name = "Żaneta Jóźwik"
                        },
                        new
                        {
                            id = 24L,
                            name = "Cecylia Misztal"
                        },
                        new
                        {
                            id = 25L,
                            name = "Sylwester Krawczyk"
                        },
                        new
                        {
                            id = 26L,
                            name = "Krystian Borowski"
                        },
                        new
                        {
                            id = 27L,
                            name = "Wiara Skowron"
                        },
                        new
                        {
                            id = 28L,
                            name = "Wincenty Żurek"
                        },
                        new
                        {
                            id = 29L,
                            name = "Piotr Bożek"
                        },
                        new
                        {
                            id = 30L,
                            name = "Ksawera Janas"
                        });
                });

            modelBuilder.Entity("BookshelfAPI.Models.Book", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("authorId")
                        .HasMaxLength(12)
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("publishDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            authorId = 115L,
                            name = "Intelligent Granite Fish",
                            publishDate = new DateTime(2023, 6, 8, 2, 56, 26, 861, DateTimeKind.Local).AddTicks(7225)
                        },
                        new
                        {
                            id = 2L,
                            authorId = 66L,
                            name = "Incredible Rubber Towels",
                            publishDate = new DateTime(2023, 9, 18, 0, 16, 34, 370, DateTimeKind.Local).AddTicks(4379)
                        },
                        new
                        {
                            id = 3L,
                            authorId = 196L,
                            name = "Generic Rubber Pants",
                            publishDate = new DateTime(2023, 10, 1, 12, 41, 18, 176, DateTimeKind.Local).AddTicks(5393)
                        },
                        new
                        {
                            id = 4L,
                            authorId = 183L,
                            name = "Practical Soft Car",
                            publishDate = new DateTime(2023, 3, 19, 13, 24, 33, 206, DateTimeKind.Local).AddTicks(8061)
                        },
                        new
                        {
                            id = 5L,
                            authorId = 135L,
                            name = "Intelligent Soft Fish",
                            publishDate = new DateTime(2023, 4, 2, 14, 35, 2, 458, DateTimeKind.Local).AddTicks(5455)
                        },
                        new
                        {
                            id = 6L,
                            authorId = 123L,
                            name = "Handcrafted Concrete Computer",
                            publishDate = new DateTime(2023, 3, 8, 12, 45, 48, 413, DateTimeKind.Local).AddTicks(2259)
                        },
                        new
                        {
                            id = 7L,
                            authorId = 110L,
                            name = "Fantastic Steel Keyboard",
                            publishDate = new DateTime(2023, 1, 24, 7, 49, 54, 415, DateTimeKind.Local).AddTicks(6156)
                        },
                        new
                        {
                            id = 8L,
                            authorId = 124L,
                            name = "Handmade Soft Car",
                            publishDate = new DateTime(2023, 5, 26, 5, 43, 48, 58, DateTimeKind.Local).AddTicks(5866)
                        },
                        new
                        {
                            id = 9L,
                            authorId = 5L,
                            name = "Incredible Cotton Mouse",
                            publishDate = new DateTime(2022, 12, 1, 3, 41, 38, 214, DateTimeKind.Local).AddTicks(4983)
                        },
                        new
                        {
                            id = 10L,
                            authorId = 115L,
                            name = "Unbranded Concrete Hat",
                            publishDate = new DateTime(2022, 11, 24, 4, 48, 14, 408, DateTimeKind.Local).AddTicks(8415)
                        },
                        new
                        {
                            id = 11L,
                            authorId = 41L,
                            name = "Incredible Concrete Car",
                            publishDate = new DateTime(2022, 12, 6, 2, 26, 32, 618, DateTimeKind.Local).AddTicks(9458)
                        },
                        new
                        {
                            id = 12L,
                            authorId = 192L,
                            name = "Handmade Plastic Tuna",
                            publishDate = new DateTime(2023, 4, 8, 14, 30, 59, 331, DateTimeKind.Local).AddTicks(4633)
                        },
                        new
                        {
                            id = 13L,
                            authorId = 170L,
                            name = "Sleek Cotton Computer",
                            publishDate = new DateTime(2023, 10, 7, 14, 15, 14, 80, DateTimeKind.Local).AddTicks(1455)
                        },
                        new
                        {
                            id = 14L,
                            authorId = 115L,
                            name = "Tasty Soft Hat",
                            publishDate = new DateTime(2022, 11, 3, 10, 35, 54, 536, DateTimeKind.Local).AddTicks(3927)
                        },
                        new
                        {
                            id = 15L,
                            authorId = 113L,
                            name = "Practical Steel Chips",
                            publishDate = new DateTime(2023, 7, 24, 16, 18, 2, 224, DateTimeKind.Local).AddTicks(6607)
                        },
                        new
                        {
                            id = 16L,
                            authorId = 28L,
                            name = "Practical Soft Shirt",
                            publishDate = new DateTime(2022, 12, 23, 20, 58, 36, 103, DateTimeKind.Local).AddTicks(367)
                        },
                        new
                        {
                            id = 17L,
                            authorId = 74L,
                            name = "Sleek Frozen Fish",
                            publishDate = new DateTime(2022, 11, 10, 16, 51, 46, 819, DateTimeKind.Local).AddTicks(2876)
                        },
                        new
                        {
                            id = 18L,
                            authorId = 88L,
                            name = "Generic Wooden Chicken",
                            publishDate = new DateTime(2022, 11, 15, 19, 13, 4, 844, DateTimeKind.Local).AddTicks(3201)
                        },
                        new
                        {
                            id = 19L,
                            authorId = 22L,
                            name = "Gorgeous Soft Ball",
                            publishDate = new DateTime(2023, 5, 19, 10, 59, 4, 852, DateTimeKind.Local).AddTicks(1914)
                        },
                        new
                        {
                            id = 20L,
                            authorId = 159L,
                            name = "Rustic Wooden Salad",
                            publishDate = new DateTime(2023, 9, 27, 12, 14, 19, 532, DateTimeKind.Local).AddTicks(1132)
                        },
                        new
                        {
                            id = 21L,
                            authorId = 146L,
                            name = "Practical Rubber Ball",
                            publishDate = new DateTime(2023, 7, 15, 6, 6, 52, 686, DateTimeKind.Local).AddTicks(73)
                        },
                        new
                        {
                            id = 22L,
                            authorId = 98L,
                            name = "Handcrafted Steel Shoes",
                            publishDate = new DateTime(2023, 3, 30, 1, 41, 55, 704, DateTimeKind.Local).AddTicks(1933)
                        },
                        new
                        {
                            id = 23L,
                            authorId = 148L,
                            name = "Unbranded Concrete Hat",
                            publishDate = new DateTime(2022, 12, 27, 1, 24, 52, 978, DateTimeKind.Local).AddTicks(7424)
                        },
                        new
                        {
                            id = 24L,
                            authorId = 161L,
                            name = "Gorgeous Concrete Shoes",
                            publishDate = new DateTime(2023, 4, 30, 14, 13, 14, 155, DateTimeKind.Local).AddTicks(4668)
                        },
                        new
                        {
                            id = 25L,
                            authorId = 67L,
                            name = "Licensed Concrete Table",
                            publishDate = new DateTime(2022, 12, 30, 14, 11, 1, 633, DateTimeKind.Local).AddTicks(8379)
                        },
                        new
                        {
                            id = 26L,
                            authorId = 162L,
                            name = "Awesome Metal Chips",
                            publishDate = new DateTime(2023, 6, 25, 6, 7, 8, 528, DateTimeKind.Local).AddTicks(6199)
                        },
                        new
                        {
                            id = 27L,
                            authorId = 128L,
                            name = "Handmade Wooden Bacon",
                            publishDate = new DateTime(2023, 8, 29, 11, 20, 17, 509, DateTimeKind.Local).AddTicks(6000)
                        },
                        new
                        {
                            id = 28L,
                            authorId = 197L,
                            name = "Sleek Steel Bacon",
                            publishDate = new DateTime(2023, 8, 9, 3, 42, 8, 596, DateTimeKind.Local).AddTicks(3288)
                        },
                        new
                        {
                            id = 29L,
                            authorId = 186L,
                            name = "Rustic Fresh Pizza",
                            publishDate = new DateTime(2022, 12, 10, 16, 35, 33, 605, DateTimeKind.Local).AddTicks(3211)
                        },
                        new
                        {
                            id = 30L,
                            authorId = 32L,
                            name = "Sleek Wooden Mouse",
                            publishDate = new DateTime(2023, 5, 9, 20, 0, 42, 604, DateTimeKind.Local).AddTicks(9492)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
