// <auto-generated />
using System;
using BookshelfAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookshelfAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookshelfAPI.Models.Author", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            name = "Hilary Maj"
                        },
                        new
                        {
                            id = 2L,
                            name = "Henryka Kołakowski"
                        },
                        new
                        {
                            id = 3L,
                            name = "Maksym Mucha"
                        },
                        new
                        {
                            id = 4L,
                            name = "Zachary Czajkowski"
                        },
                        new
                        {
                            id = 5L,
                            name = "Anna Mika"
                        },
                        new
                        {
                            id = 6L,
                            name = "Miron Bukowski"
                        },
                        new
                        {
                            id = 7L,
                            name = "Filip Staniszewski"
                        },
                        new
                        {
                            id = 8L,
                            name = "Artur Ostrowski"
                        },
                        new
                        {
                            id = 9L,
                            name = "Galfryd Smoliński"
                        },
                        new
                        {
                            id = 10L,
                            name = "Ilona Murawski"
                        },
                        new
                        {
                            id = 11L,
                            name = "Elżbieta Grzyb"
                        },
                        new
                        {
                            id = 12L,
                            name = "Cezary Piekarski"
                        },
                        new
                        {
                            id = 13L,
                            name = "Patrycy Borowski"
                        },
                        new
                        {
                            id = 14L,
                            name = "Damian Sokół"
                        },
                        new
                        {
                            id = 15L,
                            name = "Gertruda Skiba"
                        },
                        new
                        {
                            id = 16L,
                            name = "Beniamin Kucharczyk"
                        },
                        new
                        {
                            id = 17L,
                            name = "Maksym Kucharczyk"
                        },
                        new
                        {
                            id = 18L,
                            name = "Fryderyk Woźniak"
                        },
                        new
                        {
                            id = 19L,
                            name = "Roksana Gutowski"
                        },
                        new
                        {
                            id = 20L,
                            name = "Tobiasz Włodarczyk"
                        },
                        new
                        {
                            id = 21L,
                            name = "Laurencjusz Gruszczyński"
                        },
                        new
                        {
                            id = 22L,
                            name = "Bazyli Wojtas"
                        },
                        new
                        {
                            id = 23L,
                            name = "Żaneta Jóźwik"
                        },
                        new
                        {
                            id = 24L,
                            name = "Cecylia Misztal"
                        },
                        new
                        {
                            id = 25L,
                            name = "Sylwester Krawczyk"
                        },
                        new
                        {
                            id = 26L,
                            name = "Krystian Borowski"
                        },
                        new
                        {
                            id = 27L,
                            name = "Wiara Skowron"
                        },
                        new
                        {
                            id = 28L,
                            name = "Wincenty Żurek"
                        },
                        new
                        {
                            id = 29L,
                            name = "Piotr Bożek"
                        },
                        new
                        {
                            id = 30L,
                            name = "Ksawera Janas"
                        },
                        new
                        {
                            id = 31L,
                            name = "Ryszard Stefaniak"
                        },
                        new
                        {
                            id = 32L,
                            name = "Patrycjusz Tomys"
                        },
                        new
                        {
                            id = 33L,
                            name = "Serafin Woliński"
                        },
                        new
                        {
                            id = 34L,
                            name = "Helena Łukasik"
                        },
                        new
                        {
                            id = 35L,
                            name = "Alina Czyżewski"
                        },
                        new
                        {
                            id = 36L,
                            name = "Eugenia Zielonka"
                        },
                        new
                        {
                            id = 37L,
                            name = "Hugo Stawicki"
                        },
                        new
                        {
                            id = 38L,
                            name = "Joachim Kurowski"
                        },
                        new
                        {
                            id = 39L,
                            name = "Eleazar Filipek"
                        },
                        new
                        {
                            id = 40L,
                            name = "Paula Chmielewski"
                        },
                        new
                        {
                            id = 41L,
                            name = "Porfiriusz Mika"
                        },
                        new
                        {
                            id = 42L,
                            name = "Joachim Jezierski"
                        },
                        new
                        {
                            id = 43L,
                            name = "Klara Adamczak"
                        },
                        new
                        {
                            id = 44L,
                            name = "Roland Niedziela"
                        },
                        new
                        {
                            id = 45L,
                            name = "Penelopa Gadomski"
                        },
                        new
                        {
                            id = 46L,
                            name = "Szczepan Tkaczyk"
                        },
                        new
                        {
                            id = 47L,
                            name = "Igor Górecki"
                        },
                        new
                        {
                            id = 48L,
                            name = "Serafin Makowski"
                        },
                        new
                        {
                            id = 49L,
                            name = "Liza Gałka"
                        },
                        new
                        {
                            id = 50L,
                            name = "Platon Szymczyk"
                        },
                        new
                        {
                            id = 51L,
                            name = "Zachary Pilch"
                        },
                        new
                        {
                            id = 52L,
                            name = "Weronika Klimczak"
                        },
                        new
                        {
                            id = 53L,
                            name = "Franciszka Czechowski"
                        },
                        new
                        {
                            id = 54L,
                            name = "Lidia Fijałkowski"
                        },
                        new
                        {
                            id = 55L,
                            name = "Samson Buczek"
                        },
                        new
                        {
                            id = 56L,
                            name = "Lucja Grzybowski"
                        },
                        new
                        {
                            id = 57L,
                            name = "Erast Wilk"
                        },
                        new
                        {
                            id = 58L,
                            name = "Marianna Witczak"
                        },
                        new
                        {
                            id = 59L,
                            name = "Tymoteusz Chrzanowski"
                        },
                        new
                        {
                            id = 60L,
                            name = "Gerald Lewicki"
                        },
                        new
                        {
                            id = 61L,
                            name = "Rajnold Dobrowolski"
                        },
                        new
                        {
                            id = 62L,
                            name = "Bernard Kowalik"
                        },
                        new
                        {
                            id = 63L,
                            name = "Kamila Słowiński"
                        },
                        new
                        {
                            id = 64L,
                            name = "Gloria Żmuda"
                        },
                        new
                        {
                            id = 65L,
                            name = "Laurencjusz Sobolewski"
                        },
                        new
                        {
                            id = 66L,
                            name = "Cecylia Zdunek"
                        },
                        new
                        {
                            id = 67L,
                            name = "Janina Bieniek"
                        },
                        new
                        {
                            id = 68L,
                            name = "Walenty Sobczyk"
                        },
                        new
                        {
                            id = 69L,
                            name = "Agnieszka Woś"
                        },
                        new
                        {
                            id = 70L,
                            name = "Aleksandra Marczak"
                        },
                        new
                        {
                            id = 71L,
                            name = "Eleazar Jankowski"
                        },
                        new
                        {
                            id = 72L,
                            name = "Korneli Szcześniak"
                        },
                        new
                        {
                            id = 73L,
                            name = "Natanael Jagodziński"
                        },
                        new
                        {
                            id = 74L,
                            name = "Edyta Kałuża"
                        },
                        new
                        {
                            id = 75L,
                            name = "Osmund Młynarczyk"
                        },
                        new
                        {
                            id = 76L,
                            name = "Wanda Rogowski"
                        },
                        new
                        {
                            id = 77L,
                            name = "Zoe Wąsowski"
                        },
                        new
                        {
                            id = 78L,
                            name = "Orestes Książek"
                        },
                        new
                        {
                            id = 79L,
                            name = "Aleksandra Mroczkowski"
                        },
                        new
                        {
                            id = 80L,
                            name = "Helena Trojanowski"
                        },
                        new
                        {
                            id = 81L,
                            name = "Paweł Szymczak"
                        },
                        new
                        {
                            id = 82L,
                            name = "Michalina Rogowski"
                        },
                        new
                        {
                            id = 83L,
                            name = "Prokul Urban"
                        },
                        new
                        {
                            id = 84L,
                            name = "Samson Ciszewski"
                        },
                        new
                        {
                            id = 85L,
                            name = "Nazariusz Buczyński"
                        },
                        new
                        {
                            id = 86L,
                            name = "Łazarz Niemczyk"
                        },
                        new
                        {
                            id = 87L,
                            name = "Teodor Przybysz"
                        },
                        new
                        {
                            id = 88L,
                            name = "Leonard Dziedzic"
                        },
                        new
                        {
                            id = 89L,
                            name = "Aleksander Górski"
                        },
                        new
                        {
                            id = 90L,
                            name = "Alwar Klimczak"
                        },
                        new
                        {
                            id = 91L,
                            name = "Emanuel Komorowski"
                        },
                        new
                        {
                            id = 92L,
                            name = "Alina Rudziński"
                        },
                        new
                        {
                            id = 93L,
                            name = "Justyna Wójcik"
                        },
                        new
                        {
                            id = 94L,
                            name = "Teodora Szczepaniak"
                        },
                        new
                        {
                            id = 95L,
                            name = "Daria Cebula"
                        },
                        new
                        {
                            id = 96L,
                            name = "Ernest Adamczyk"
                        },
                        new
                        {
                            id = 97L,
                            name = "Franciszek Rybarczyk"
                        },
                        new
                        {
                            id = 98L,
                            name = "Konrad Kalinowski"
                        },
                        new
                        {
                            id = 99L,
                            name = "Filemon Krakowiak"
                        },
                        new
                        {
                            id = 100L,
                            name = "Onufry Maciejewski"
                        },
                        new
                        {
                            id = 101L,
                            name = "Laurentyna Mierzejewski"
                        },
                        new
                        {
                            id = 102L,
                            name = "Wirginia Kacprzak"
                        },
                        new
                        {
                            id = 103L,
                            name = "Gerald Kot"
                        },
                        new
                        {
                            id = 104L,
                            name = "Franciszek Jędrzejczyk"
                        },
                        new
                        {
                            id = 105L,
                            name = "Barbara Gruszczyński"
                        },
                        new
                        {
                            id = 106L,
                            name = "Patrycjusz Karaś"
                        },
                        new
                        {
                            id = 107L,
                            name = "Walgierz Komorowski"
                        },
                        new
                        {
                            id = 108L,
                            name = "Emilia Bednarz"
                        },
                        new
                        {
                            id = 109L,
                            name = "Hilarion Dominiak"
                        },
                        new
                        {
                            id = 110L,
                            name = "Ruta Madej"
                        },
                        new
                        {
                            id = 111L,
                            name = "Paulina Pietrzak"
                        },
                        new
                        {
                            id = 112L,
                            name = "Rajnold Jagiełło"
                        },
                        new
                        {
                            id = 113L,
                            name = "Filipa Jędrzejczak"
                        },
                        new
                        {
                            id = 114L,
                            name = "Patrycjusz Staniszewski"
                        },
                        new
                        {
                            id = 115L,
                            name = "Adelajda Żak"
                        },
                        new
                        {
                            id = 116L,
                            name = "Izolda Nowakowski"
                        },
                        new
                        {
                            id = 117L,
                            name = "Maja Matusiak"
                        },
                        new
                        {
                            id = 118L,
                            name = "Ksawery Olejnik"
                        },
                        new
                        {
                            id = 119L,
                            name = "Oliwier Jakubowski"
                        },
                        new
                        {
                            id = 120L,
                            name = "Rafał Kowalczuk"
                        },
                        new
                        {
                            id = 121L,
                            name = "Irena Pawłowski"
                        },
                        new
                        {
                            id = 122L,
                            name = "Gabriel Kucharski"
                        },
                        new
                        {
                            id = 123L,
                            name = "Elwira Szymański"
                        },
                        new
                        {
                            id = 124L,
                            name = "Reginald Szcześniak"
                        },
                        new
                        {
                            id = 125L,
                            name = "Antoni Bogucki"
                        },
                        new
                        {
                            id = 126L,
                            name = "Bertram Jabłoński"
                        },
                        new
                        {
                            id = 127L,
                            name = "Salwator Wawrzyniak"
                        },
                        new
                        {
                            id = 128L,
                            name = "Aleksandra Czerwiński"
                        },
                        new
                        {
                            id = 129L,
                            name = "Klaudiusz Romanowski"
                        },
                        new
                        {
                            id = 130L,
                            name = "Patrycy Zielonka"
                        },
                        new
                        {
                            id = 131L,
                            name = "Wiktoria Kozłowski"
                        },
                        new
                        {
                            id = 132L,
                            name = "Ilona Pakuła"
                        },
                        new
                        {
                            id = 133L,
                            name = "Rudolf Stec"
                        },
                        new
                        {
                            id = 134L,
                            name = "Reginald Bagiński"
                        },
                        new
                        {
                            id = 135L,
                            name = "Lilianna Borowski"
                        },
                        new
                        {
                            id = 136L,
                            name = "Klementyna Zwoliński"
                        },
                        new
                        {
                            id = 137L,
                            name = "Ewelina Mazurkiewicz"
                        },
                        new
                        {
                            id = 138L,
                            name = "Joanna Hajduk"
                        },
                        new
                        {
                            id = 139L,
                            name = "Roger Adamus"
                        },
                        new
                        {
                            id = 140L,
                            name = "Agrypina Bogucki"
                        },
                        new
                        {
                            id = 141L,
                            name = "Maja Mróz"
                        },
                        new
                        {
                            id = 142L,
                            name = "Joanna Malec"
                        },
                        new
                        {
                            id = 143L,
                            name = "Paulina Lesiak"
                        },
                        new
                        {
                            id = 144L,
                            name = "Damian Łukasik"
                        },
                        new
                        {
                            id = 145L,
                            name = "Sylwia Krzyżanowski"
                        },
                        new
                        {
                            id = 146L,
                            name = "Terencjusz Pluta"
                        },
                        new
                        {
                            id = 147L,
                            name = "Melania Lenart"
                        },
                        new
                        {
                            id = 148L,
                            name = "Patrycy Karczewski"
                        },
                        new
                        {
                            id = 149L,
                            name = "Rachela Milczarek"
                        },
                        new
                        {
                            id = 150L,
                            name = "Walentyna Wieczorek"
                        },
                        new
                        {
                            id = 151L,
                            name = "Natanael Książek"
                        },
                        new
                        {
                            id = 152L,
                            name = "Alan Zielonka"
                        },
                        new
                        {
                            id = 153L,
                            name = "Patrycjusz Cichoń"
                        },
                        new
                        {
                            id = 154L,
                            name = "Ksawery Włodarczyk"
                        },
                        new
                        {
                            id = 155L,
                            name = "Cyrus Kalisz"
                        },
                        new
                        {
                            id = 156L,
                            name = "Dorota Bąkowski"
                        },
                        new
                        {
                            id = 157L,
                            name = "Cyrus Kasprzyk"
                        },
                        new
                        {
                            id = 158L,
                            name = "Klarencjusz Kowalski"
                        },
                        new
                        {
                            id = 159L,
                            name = "Krystyna Gruszka"
                        },
                        new
                        {
                            id = 160L,
                            name = "Gracja Żuk"
                        },
                        new
                        {
                            id = 161L,
                            name = "Dina Lisiecki"
                        },
                        new
                        {
                            id = 162L,
                            name = "Bertrand Kos"
                        },
                        new
                        {
                            id = 163L,
                            name = "Wilfryd Śliwiński"
                        },
                        new
                        {
                            id = 164L,
                            name = "Klaudiusz Gruszka"
                        },
                        new
                        {
                            id = 165L,
                            name = "Damian Kruszewski"
                        },
                        new
                        {
                            id = 166L,
                            name = "Maksym Witek"
                        },
                        new
                        {
                            id = 167L,
                            name = "Apollo Raczyński"
                        },
                        new
                        {
                            id = 168L,
                            name = "Eugenia Kubacki"
                        },
                        new
                        {
                            id = 169L,
                            name = "Jerzy Stanek"
                        },
                        new
                        {
                            id = 170L,
                            name = "Klaudiusz Stefaniak"
                        },
                        new
                        {
                            id = 171L,
                            name = "Renata Flis"
                        },
                        new
                        {
                            id = 172L,
                            name = "Marta Nowiński"
                        },
                        new
                        {
                            id = 173L,
                            name = "Joanna Kruszewski"
                        },
                        new
                        {
                            id = 174L,
                            name = "Błażej Marcinkowski"
                        },
                        new
                        {
                            id = 175L,
                            name = "Mikołaj Andrzejewski"
                        },
                        new
                        {
                            id = 176L,
                            name = "Elwira Przybysz"
                        },
                        new
                        {
                            id = 177L,
                            name = "Małgorzata Łapiński"
                        },
                        new
                        {
                            id = 178L,
                            name = "Grzegorz Urbaniak"
                        },
                        new
                        {
                            id = 179L,
                            name = "Maksymilian Partyka"
                        },
                        new
                        {
                            id = 180L,
                            name = "Patryk Krzyżanowski"
                        },
                        new
                        {
                            id = 181L,
                            name = "Abraham Karczewski"
                        },
                        new
                        {
                            id = 182L,
                            name = "Lilla Robak"
                        },
                        new
                        {
                            id = 183L,
                            name = "Wiktoria Sowa"
                        },
                        new
                        {
                            id = 184L,
                            name = "Arkadiusz Królikowski"
                        },
                        new
                        {
                            id = 185L,
                            name = "Karolina Piątek"
                        },
                        new
                        {
                            id = 186L,
                            name = "Lucja Trojanowski"
                        },
                        new
                        {
                            id = 187L,
                            name = "Korneli Wrona"
                        },
                        new
                        {
                            id = 188L,
                            name = "Bernard Lewandowski"
                        },
                        new
                        {
                            id = 189L,
                            name = "Katarzyna Kwiecień"
                        },
                        new
                        {
                            id = 190L,
                            name = "Berta Czyż"
                        },
                        new
                        {
                            id = 191L,
                            name = "Prokles Mucha"
                        },
                        new
                        {
                            id = 192L,
                            name = "Maryna Cieśla"
                        },
                        new
                        {
                            id = 193L,
                            name = "Ida Pilarski"
                        },
                        new
                        {
                            id = 194L,
                            name = "Arnold Borkowski"
                        },
                        new
                        {
                            id = 195L,
                            name = "Samuel Szczęsna"
                        },
                        new
                        {
                            id = 196L,
                            name = "Bertram Wypych"
                        },
                        new
                        {
                            id = 197L,
                            name = "Olaf Polak"
                        },
                        new
                        {
                            id = 198L,
                            name = "Laurentyna Mroczkowski"
                        },
                        new
                        {
                            id = 199L,
                            name = "Nestor Dominiak"
                        },
                        new
                        {
                            id = 200L,
                            name = "Karolina Łukasiewicz"
                        });
                });

            modelBuilder.Entity("BookshelfAPI.Models.Book", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("authorId")
                        .HasMaxLength(12)
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("publishDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            authorId = 111L,
                            name = "Intelligent Granite Fish",
                            publishDate = new DateTime(2023, 6, 9, 22, 32, 29, 276, DateTimeKind.Local).AddTicks(3717)
                        },
                        new
                        {
                            id = 2L,
                            authorId = 33L,
                            name = "Incredible Rubber Towels",
                            publishDate = new DateTime(2023, 9, 19, 19, 52, 36, 785, DateTimeKind.Local).AddTicks(395)
                        },
                        new
                        {
                            id = 3L,
                            authorId = 167L,
                            name = "Generic Rubber Pants",
                            publishDate = new DateTime(2023, 10, 3, 8, 17, 20, 591, DateTimeKind.Local).AddTicks(1427)
                        },
                        new
                        {
                            id = 4L,
                            authorId = 27L,
                            name = "Practical Soft Car",
                            publishDate = new DateTime(2023, 3, 21, 9, 0, 35, 621, DateTimeKind.Local).AddTicks(4181)
                        },
                        new
                        {
                            id = 5L,
                            authorId = 50L,
                            name = "Intelligent Soft Fish",
                            publishDate = new DateTime(2023, 4, 4, 10, 11, 4, 873, DateTimeKind.Local).AddTicks(1565)
                        },
                        new
                        {
                            id = 6L,
                            authorId = 104L,
                            name = "Handcrafted Concrete Computer",
                            publishDate = new DateTime(2023, 3, 10, 8, 21, 50, 827, DateTimeKind.Local).AddTicks(8363)
                        },
                        new
                        {
                            id = 7L,
                            authorId = 22L,
                            name = "Fantastic Steel Keyboard",
                            publishDate = new DateTime(2023, 1, 26, 3, 25, 56, 830, DateTimeKind.Local).AddTicks(2242)
                        },
                        new
                        {
                            id = 8L,
                            authorId = 146L,
                            name = "Handmade Soft Car",
                            publishDate = new DateTime(2023, 5, 28, 1, 19, 50, 473, DateTimeKind.Local).AddTicks(1945)
                        },
                        new
                        {
                            id = 9L,
                            authorId = 90L,
                            name = "Incredible Cotton Mouse",
                            publishDate = new DateTime(2022, 12, 2, 23, 17, 40, 629, DateTimeKind.Local).AddTicks(1043)
                        },
                        new
                        {
                            id = 10L,
                            authorId = 144L,
                            name = "Unbranded Concrete Hat",
                            publishDate = new DateTime(2022, 11, 26, 0, 24, 16, 823, DateTimeKind.Local).AddTicks(4457)
                        },
                        new
                        {
                            id = 11L,
                            authorId = 192L,
                            name = "Incredible Concrete Car",
                            publishDate = new DateTime(2022, 12, 7, 22, 2, 35, 33, DateTimeKind.Local).AddTicks(5490)
                        },
                        new
                        {
                            id = 12L,
                            authorId = 102L,
                            name = "Handmade Plastic Tuna",
                            publishDate = new DateTime(2023, 4, 10, 10, 7, 1, 746, DateTimeKind.Local).AddTicks(656)
                        },
                        new
                        {
                            id = 13L,
                            authorId = 128L,
                            name = "Sleek Cotton Computer",
                            publishDate = new DateTime(2023, 10, 9, 9, 51, 16, 494, DateTimeKind.Local).AddTicks(7468)
                        },
                        new
                        {
                            id = 14L,
                            authorId = 163L,
                            name = "Tasty Soft Hat",
                            publishDate = new DateTime(2022, 11, 5, 6, 11, 56, 950, DateTimeKind.Local).AddTicks(9932)
                        },
                        new
                        {
                            id = 15L,
                            authorId = 45L,
                            name = "Practical Steel Chips",
                            publishDate = new DateTime(2023, 7, 26, 11, 54, 4, 639, DateTimeKind.Local).AddTicks(2593)
                        },
                        new
                        {
                            id = 16L,
                            authorId = 92L,
                            name = "Practical Soft Shirt",
                            publishDate = new DateTime(2022, 12, 25, 16, 34, 38, 517, DateTimeKind.Local).AddTicks(6253)
                        },
                        new
                        {
                            id = 17L,
                            authorId = 19L,
                            name = "Sleek Frozen Fish",
                            publishDate = new DateTime(2022, 11, 12, 12, 27, 49, 233, DateTimeKind.Local).AddTicks(8752)
                        },
                        new
                        {
                            id = 18L,
                            authorId = 110L,
                            name = "Generic Wooden Chicken",
                            publishDate = new DateTime(2022, 11, 17, 14, 49, 7, 258, DateTimeKind.Local).AddTicks(9077)
                        },
                        new
                        {
                            id = 19L,
                            authorId = 55L,
                            name = "Gorgeous Soft Ball",
                            publishDate = new DateTime(2023, 5, 21, 6, 35, 7, 266, DateTimeKind.Local).AddTicks(7815)
                        },
                        new
                        {
                            id = 20L,
                            authorId = 131L,
                            name = "Rustic Wooden Salad",
                            publishDate = new DateTime(2023, 9, 29, 7, 50, 21, 946, DateTimeKind.Local).AddTicks(7035)
                        },
                        new
                        {
                            id = 21L,
                            authorId = 135L,
                            name = "Practical Rubber Ball",
                            publishDate = new DateTime(2023, 7, 17, 1, 42, 55, 100, DateTimeKind.Local).AddTicks(5976)
                        },
                        new
                        {
                            id = 22L,
                            authorId = 108L,
                            name = "Handcrafted Steel Shoes",
                            publishDate = new DateTime(2023, 3, 31, 21, 17, 58, 118, DateTimeKind.Local).AddTicks(7837)
                        },
                        new
                        {
                            id = 23L,
                            authorId = 54L,
                            name = "Unbranded Concrete Hat",
                            publishDate = new DateTime(2022, 12, 28, 21, 0, 55, 393, DateTimeKind.Local).AddTicks(3330)
                        },
                        new
                        {
                            id = 24L,
                            authorId = 83L,
                            name = "Gorgeous Concrete Shoes",
                            publishDate = new DateTime(2023, 5, 2, 9, 49, 16, 570, DateTimeKind.Local).AddTicks(564)
                        },
                        new
                        {
                            id = 25L,
                            authorId = 43L,
                            name = "Licensed Concrete Table",
                            publishDate = new DateTime(2023, 1, 1, 9, 47, 4, 48, DateTimeKind.Local).AddTicks(4275)
                        },
                        new
                        {
                            id = 26L,
                            authorId = 101L,
                            name = "Awesome Metal Chips",
                            publishDate = new DateTime(2023, 6, 27, 1, 43, 10, 943, DateTimeKind.Local).AddTicks(2095)
                        },
                        new
                        {
                            id = 27L,
                            authorId = 97L,
                            name = "Handmade Wooden Bacon",
                            publishDate = new DateTime(2023, 8, 31, 6, 56, 19, 924, DateTimeKind.Local).AddTicks(1887)
                        },
                        new
                        {
                            id = 28L,
                            authorId = 62L,
                            name = "Sleek Steel Bacon",
                            publishDate = new DateTime(2023, 8, 10, 23, 18, 11, 10, DateTimeKind.Local).AddTicks(9176)
                        },
                        new
                        {
                            id = 29L,
                            authorId = 22L,
                            name = "Rustic Fresh Pizza",
                            publishDate = new DateTime(2022, 12, 12, 12, 11, 36, 19, DateTimeKind.Local).AddTicks(9098)
                        },
                        new
                        {
                            id = 30L,
                            authorId = 145L,
                            name = "Sleek Wooden Mouse",
                            publishDate = new DateTime(2023, 5, 11, 15, 36, 45, 19, DateTimeKind.Local).AddTicks(5379)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
