// <auto-generated />
using System;
using BookshelfAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookshelfAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookshelfAPI.Models.Author", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            name = "Hilary Maj"
                        },
                        new
                        {
                            id = 2L,
                            name = "Henryka Kołakowski"
                        },
                        new
                        {
                            id = 3L,
                            name = "Maksym Mucha"
                        },
                        new
                        {
                            id = 4L,
                            name = "Zachary Czajkowski"
                        },
                        new
                        {
                            id = 5L,
                            name = "Anna Mika"
                        },
                        new
                        {
                            id = 6L,
                            name = "Miron Bukowski"
                        },
                        new
                        {
                            id = 7L,
                            name = "Filip Staniszewski"
                        },
                        new
                        {
                            id = 8L,
                            name = "Artur Ostrowski"
                        },
                        new
                        {
                            id = 9L,
                            name = "Galfryd Smoliński"
                        },
                        new
                        {
                            id = 10L,
                            name = "Ilona Murawski"
                        },
                        new
                        {
                            id = 11L,
                            name = "Elżbieta Grzyb"
                        },
                        new
                        {
                            id = 12L,
                            name = "Cezary Piekarski"
                        },
                        new
                        {
                            id = 13L,
                            name = "Patrycy Borowski"
                        },
                        new
                        {
                            id = 14L,
                            name = "Damian Sokół"
                        },
                        new
                        {
                            id = 15L,
                            name = "Gertruda Skiba"
                        },
                        new
                        {
                            id = 16L,
                            name = "Beniamin Kucharczyk"
                        },
                        new
                        {
                            id = 17L,
                            name = "Maksym Kucharczyk"
                        },
                        new
                        {
                            id = 18L,
                            name = "Fryderyk Woźniak"
                        },
                        new
                        {
                            id = 19L,
                            name = "Roksana Gutowski"
                        },
                        new
                        {
                            id = 20L,
                            name = "Tobiasz Włodarczyk"
                        },
                        new
                        {
                            id = 21L,
                            name = "Laurencjusz Gruszczyński"
                        },
                        new
                        {
                            id = 22L,
                            name = "Bazyli Wojtas"
                        },
                        new
                        {
                            id = 23L,
                            name = "Żaneta Jóźwik"
                        },
                        new
                        {
                            id = 24L,
                            name = "Cecylia Misztal"
                        },
                        new
                        {
                            id = 25L,
                            name = "Sylwester Krawczyk"
                        },
                        new
                        {
                            id = 26L,
                            name = "Krystian Borowski"
                        },
                        new
                        {
                            id = 27L,
                            name = "Wiara Skowron"
                        },
                        new
                        {
                            id = 28L,
                            name = "Wincenty Żurek"
                        },
                        new
                        {
                            id = 29L,
                            name = "Piotr Bożek"
                        },
                        new
                        {
                            id = 30L,
                            name = "Ksawera Janas"
                        });
                });

            modelBuilder.Entity("BookshelfAPI.Models.Book", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("authorId")
                        .HasMaxLength(12)
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("publishDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            authorId = 18L,
                            name = "Intelligent Granite Fish",
                            publishDate = new DateTime(2023, 6, 17, 0, 6, 0, 435, DateTimeKind.Local).AddTicks(4898)
                        },
                        new
                        {
                            id = 2L,
                            authorId = 14L,
                            name = "Incredible Rubber Towels",
                            publishDate = new DateTime(2023, 9, 26, 21, 26, 7, 944, DateTimeKind.Local).AddTicks(1121)
                        },
                        new
                        {
                            id = 3L,
                            authorId = 18L,
                            name = "Generic Rubber Pants",
                            publishDate = new DateTime(2023, 10, 10, 9, 50, 51, 750, DateTimeKind.Local).AddTicks(2113)
                        },
                        new
                        {
                            id = 4L,
                            authorId = 19L,
                            name = "Practical Soft Car",
                            publishDate = new DateTime(2023, 3, 28, 10, 34, 6, 780, DateTimeKind.Local).AddTicks(4770)
                        },
                        new
                        {
                            id = 5L,
                            authorId = 2L,
                            name = "Intelligent Soft Fish",
                            publishDate = new DateTime(2023, 4, 11, 11, 44, 36, 32, DateTimeKind.Local).AddTicks(2146)
                        },
                        new
                        {
                            id = 6L,
                            authorId = 9L,
                            name = "Handcrafted Concrete Computer",
                            publishDate = new DateTime(2023, 3, 17, 9, 55, 21, 986, DateTimeKind.Local).AddTicks(8943)
                        },
                        new
                        {
                            id = 7L,
                            authorId = 24L,
                            name = "Fantastic Steel Keyboard",
                            publishDate = new DateTime(2023, 2, 2, 4, 59, 27, 989, DateTimeKind.Local).AddTicks(2881)
                        },
                        new
                        {
                            id = 8L,
                            authorId = 4L,
                            name = "Handmade Soft Car",
                            publishDate = new DateTime(2023, 6, 4, 2, 53, 21, 632, DateTimeKind.Local).AddTicks(2587)
                        },
                        new
                        {
                            id = 9L,
                            authorId = 23L,
                            name = "Incredible Cotton Mouse",
                            publishDate = new DateTime(2022, 12, 10, 0, 51, 11, 788, DateTimeKind.Local).AddTicks(1686)
                        },
                        new
                        {
                            id = 10L,
                            authorId = 29L,
                            name = "Unbranded Concrete Hat",
                            publishDate = new DateTime(2022, 12, 3, 1, 57, 47, 982, DateTimeKind.Local).AddTicks(5099)
                        },
                        new
                        {
                            id = 11L,
                            authorId = 18L,
                            name = "Incredible Concrete Car",
                            publishDate = new DateTime(2022, 12, 14, 23, 36, 6, 192, DateTimeKind.Local).AddTicks(6133)
                        },
                        new
                        {
                            id = 12L,
                            authorId = 10L,
                            name = "Handmade Plastic Tuna",
                            publishDate = new DateTime(2023, 4, 17, 11, 40, 32, 905, DateTimeKind.Local).AddTicks(1299)
                        },
                        new
                        {
                            id = 13L,
                            authorId = 29L,
                            name = "Sleek Cotton Computer",
                            publishDate = new DateTime(2023, 10, 16, 11, 24, 47, 653, DateTimeKind.Local).AddTicks(8111)
                        },
                        new
                        {
                            id = 14L,
                            authorId = 16L,
                            name = "Tasty Soft Hat",
                            publishDate = new DateTime(2022, 11, 12, 7, 45, 28, 110, DateTimeKind.Local).AddTicks(574)
                        },
                        new
                        {
                            id = 15L,
                            authorId = 10L,
                            name = "Practical Steel Chips",
                            publishDate = new DateTime(2023, 8, 2, 13, 27, 35, 798, DateTimeKind.Local).AddTicks(3235)
                        },
                        new
                        {
                            id = 16L,
                            authorId = 12L,
                            name = "Practical Soft Shirt",
                            publishDate = new DateTime(2023, 1, 1, 18, 8, 9, 676, DateTimeKind.Local).AddTicks(6896)
                        },
                        new
                        {
                            id = 17L,
                            authorId = 3L,
                            name = "Sleek Frozen Fish",
                            publishDate = new DateTime(2022, 11, 19, 14, 1, 20, 392, DateTimeKind.Local).AddTicks(9396)
                        },
                        new
                        {
                            id = 18L,
                            authorId = 12L,
                            name = "Generic Wooden Chicken",
                            publishDate = new DateTime(2022, 11, 24, 16, 22, 38, 417, DateTimeKind.Local).AddTicks(9722)
                        },
                        new
                        {
                            id = 19L,
                            authorId = 23L,
                            name = "Gorgeous Soft Ball",
                            publishDate = new DateTime(2023, 5, 28, 8, 8, 38, 425, DateTimeKind.Local).AddTicks(8425)
                        },
                        new
                        {
                            id = 20L,
                            authorId = 20L,
                            name = "Rustic Wooden Salad",
                            publishDate = new DateTime(2023, 10, 6, 9, 23, 53, 105, DateTimeKind.Local).AddTicks(7644)
                        },
                        new
                        {
                            id = 21L,
                            authorId = 25L,
                            name = "Practical Rubber Ball",
                            publishDate = new DateTime(2023, 7, 24, 3, 16, 26, 259, DateTimeKind.Local).AddTicks(6586)
                        },
                        new
                        {
                            id = 22L,
                            authorId = 6L,
                            name = "Handcrafted Steel Shoes",
                            publishDate = new DateTime(2023, 4, 7, 22, 51, 29, 277, DateTimeKind.Local).AddTicks(8483)
                        },
                        new
                        {
                            id = 23L,
                            authorId = 8L,
                            name = "Unbranded Concrete Hat",
                            publishDate = new DateTime(2023, 1, 4, 22, 34, 26, 552, DateTimeKind.Local).AddTicks(3977)
                        },
                        new
                        {
                            id = 24L,
                            authorId = 23L,
                            name = "Gorgeous Concrete Shoes",
                            publishDate = new DateTime(2023, 5, 9, 11, 22, 47, 729, DateTimeKind.Local).AddTicks(1211)
                        },
                        new
                        {
                            id = 25L,
                            authorId = 11L,
                            name = "Licensed Concrete Table",
                            publishDate = new DateTime(2023, 1, 8, 11, 20, 35, 207, DateTimeKind.Local).AddTicks(4922)
                        },
                        new
                        {
                            id = 26L,
                            authorId = 13L,
                            name = "Awesome Metal Chips",
                            publishDate = new DateTime(2023, 7, 4, 3, 16, 42, 102, DateTimeKind.Local).AddTicks(2742)
                        },
                        new
                        {
                            id = 27L,
                            authorId = 22L,
                            name = "Handmade Wooden Bacon",
                            publishDate = new DateTime(2023, 9, 7, 8, 29, 51, 83, DateTimeKind.Local).AddTicks(2533)
                        },
                        new
                        {
                            id = 28L,
                            authorId = 29L,
                            name = "Sleek Steel Bacon",
                            publishDate = new DateTime(2023, 8, 18, 0, 51, 42, 169, DateTimeKind.Local).AddTicks(9822)
                        },
                        new
                        {
                            id = 29L,
                            authorId = 9L,
                            name = "Rustic Fresh Pizza",
                            publishDate = new DateTime(2022, 12, 19, 13, 45, 7, 178, DateTimeKind.Local).AddTicks(9744)
                        },
                        new
                        {
                            id = 30L,
                            authorId = 8L,
                            name = "Sleek Wooden Mouse",
                            publishDate = new DateTime(2023, 5, 18, 17, 10, 16, 178, DateTimeKind.Local).AddTicks(6025)
                        },
                        new
                        {
                            id = 31L,
                            authorId = 9L,
                            name = "Practical Wooden Car",
                            publishDate = new DateTime(2023, 6, 20, 3, 11, 50, 908, DateTimeKind.Local).AddTicks(2490)
                        },
                        new
                        {
                            id = 32L,
                            authorId = 7L,
                            name = "Generic Fresh Fish",
                            publishDate = new DateTime(2022, 11, 14, 10, 38, 44, 162, DateTimeKind.Local).AddTicks(9879)
                        },
                        new
                        {
                            id = 33L,
                            authorId = 10L,
                            name = "Incredible Soft Tuna",
                            publishDate = new DateTime(2022, 11, 25, 21, 41, 51, 660, DateTimeKind.Local).AddTicks(2548)
                        },
                        new
                        {
                            id = 34L,
                            authorId = 7L,
                            name = "Handmade Steel Hat",
                            publishDate = new DateTime(2023, 2, 5, 7, 22, 20, 801, DateTimeKind.Local).AddTicks(9956)
                        },
                        new
                        {
                            id = 35L,
                            authorId = 26L,
                            name = "Awesome Frozen Soap",
                            publishDate = new DateTime(2023, 5, 5, 10, 18, 36, 715, DateTimeKind.Local).AddTicks(3484)
                        },
                        new
                        {
                            id = 36L,
                            authorId = 29L,
                            name = "Rustic Plastic Computer",
                            publishDate = new DateTime(2023, 1, 15, 1, 52, 13, 86, DateTimeKind.Local).AddTicks(5396)
                        },
                        new
                        {
                            id = 37L,
                            authorId = 3L,
                            name = "Fantastic Plastic Chicken",
                            publishDate = new DateTime(2023, 7, 6, 17, 24, 3, 460, DateTimeKind.Local).AddTicks(2737)
                        },
                        new
                        {
                            id = 38L,
                            authorId = 12L,
                            name = "Fantastic Rubber Chips",
                            publishDate = new DateTime(2023, 2, 25, 20, 49, 45, 535, DateTimeKind.Local).AddTicks(8439)
                        },
                        new
                        {
                            id = 39L,
                            authorId = 4L,
                            name = "Tasty Frozen Shirt",
                            publishDate = new DateTime(2023, 6, 7, 11, 50, 30, 634, DateTimeKind.Local).AddTicks(1177)
                        },
                        new
                        {
                            id = 40L,
                            authorId = 8L,
                            name = "Generic Rubber Fish",
                            publishDate = new DateTime(2022, 12, 31, 13, 18, 22, 390, DateTimeKind.Local).AddTicks(5209)
                        },
                        new
                        {
                            id = 41L,
                            authorId = 14L,
                            name = "Practical Fresh Pizza",
                            publishDate = new DateTime(2023, 2, 25, 22, 47, 29, 403, DateTimeKind.Local).AddTicks(9960)
                        },
                        new
                        {
                            id = 42L,
                            authorId = 9L,
                            name = "Practical Fresh Shoes",
                            publishDate = new DateTime(2023, 9, 29, 2, 36, 35, 154, DateTimeKind.Local).AddTicks(294)
                        },
                        new
                        {
                            id = 43L,
                            authorId = 18L,
                            name = "Fantastic Steel Gloves",
                            publishDate = new DateTime(2023, 4, 6, 6, 31, 8, 350, DateTimeKind.Local).AddTicks(3656)
                        },
                        new
                        {
                            id = 44L,
                            authorId = 5L,
                            name = "Sleek Metal Gloves",
                            publishDate = new DateTime(2023, 9, 12, 1, 18, 37, 1, DateTimeKind.Local).AddTicks(3329)
                        },
                        new
                        {
                            id = 45L,
                            authorId = 9L,
                            name = "Small Concrete Chair",
                            publishDate = new DateTime(2023, 7, 4, 3, 5, 12, 328, DateTimeKind.Local).AddTicks(7495)
                        },
                        new
                        {
                            id = 46L,
                            authorId = 14L,
                            name = "Rustic Cotton Soap",
                            publishDate = new DateTime(2023, 2, 21, 20, 6, 47, 675, DateTimeKind.Local).AddTicks(6913)
                        },
                        new
                        {
                            id = 47L,
                            authorId = 7L,
                            name = "Licensed Frozen Chips",
                            publishDate = new DateTime(2023, 1, 16, 22, 57, 32, 30, DateTimeKind.Local).AddTicks(9951)
                        },
                        new
                        {
                            id = 48L,
                            authorId = 4L,
                            name = "Handcrafted Wooden Mouse",
                            publishDate = new DateTime(2023, 11, 10, 23, 48, 53, 629, DateTimeKind.Local).AddTicks(8139)
                        },
                        new
                        {
                            id = 49L,
                            authorId = 9L,
                            name = "Intelligent Metal Computer",
                            publishDate = new DateTime(2023, 7, 15, 4, 2, 14, 862, DateTimeKind.Local).AddTicks(5185)
                        },
                        new
                        {
                            id = 50L,
                            authorId = 21L,
                            name = "Practical Cotton Shirt",
                            publishDate = new DateTime(2023, 5, 14, 2, 53, 9, 145, DateTimeKind.Local).AddTicks(735)
                        },
                        new
                        {
                            id = 51L,
                            authorId = 19L,
                            name = "Licensed Rubber Chips",
                            publishDate = new DateTime(2023, 7, 19, 0, 51, 3, 683, DateTimeKind.Local).AddTicks(8245)
                        },
                        new
                        {
                            id = 52L,
                            authorId = 25L,
                            name = "Gorgeous Cotton Mouse",
                            publishDate = new DateTime(2023, 7, 20, 5, 9, 5, 402, DateTimeKind.Local).AddTicks(8376)
                        },
                        new
                        {
                            id = 53L,
                            authorId = 2L,
                            name = "Generic Concrete Shirt",
                            publishDate = new DateTime(2023, 7, 11, 15, 58, 43, 601, DateTimeKind.Local).AddTicks(9388)
                        },
                        new
                        {
                            id = 54L,
                            authorId = 16L,
                            name = "Awesome Cotton Chicken",
                            publishDate = new DateTime(2023, 10, 26, 19, 44, 40, 851, DateTimeKind.Local).AddTicks(7271)
                        },
                        new
                        {
                            id = 55L,
                            authorId = 21L,
                            name = "Gorgeous Wooden Sausages",
                            publishDate = new DateTime(2023, 5, 12, 14, 15, 21, 887, DateTimeKind.Local).AddTicks(8415)
                        },
                        new
                        {
                            id = 56L,
                            authorId = 25L,
                            name = "Unbranded Metal Table",
                            publishDate = new DateTime(2023, 8, 4, 11, 2, 37, 660, DateTimeKind.Local).AddTicks(1588)
                        },
                        new
                        {
                            id = 57L,
                            authorId = 3L,
                            name = "Unbranded Plastic Shirt",
                            publishDate = new DateTime(2023, 1, 27, 12, 5, 18, 791, DateTimeKind.Local).AddTicks(3612)
                        },
                        new
                        {
                            id = 58L,
                            authorId = 1L,
                            name = "Awesome Frozen Fish",
                            publishDate = new DateTime(2023, 4, 3, 0, 19, 43, 374, DateTimeKind.Local).AddTicks(9461)
                        },
                        new
                        {
                            id = 59L,
                            authorId = 21L,
                            name = "Refined Granite Towels",
                            publishDate = new DateTime(2023, 3, 31, 9, 51, 33, 328, DateTimeKind.Local).AddTicks(7163)
                        },
                        new
                        {
                            id = 60L,
                            authorId = 1L,
                            name = "Fantastic Plastic Table",
                            publishDate = new DateTime(2023, 6, 21, 23, 41, 37, 371, DateTimeKind.Local).AddTicks(4563)
                        },
                        new
                        {
                            id = 61L,
                            authorId = 5L,
                            name = "Handmade Metal Mouse",
                            publishDate = new DateTime(2023, 6, 3, 6, 23, 1, 733, DateTimeKind.Local).AddTicks(6128)
                        },
                        new
                        {
                            id = 62L,
                            authorId = 12L,
                            name = "Handcrafted Fresh Table",
                            publishDate = new DateTime(2023, 1, 14, 20, 53, 59, 724, DateTimeKind.Local).AddTicks(9829)
                        },
                        new
                        {
                            id = 63L,
                            authorId = 19L,
                            name = "Small Steel Car",
                            publishDate = new DateTime(2023, 8, 5, 19, 5, 3, 128, DateTimeKind.Local).AddTicks(9341)
                        },
                        new
                        {
                            id = 64L,
                            authorId = 11L,
                            name = "Sleek Fresh Soap",
                            publishDate = new DateTime(2023, 9, 23, 1, 51, 48, 648, DateTimeKind.Local).AddTicks(9142)
                        },
                        new
                        {
                            id = 65L,
                            authorId = 6L,
                            name = "Ergonomic Metal Shirt",
                            publishDate = new DateTime(2022, 11, 24, 15, 5, 53, 275, DateTimeKind.Local).AddTicks(2831)
                        },
                        new
                        {
                            id = 66L,
                            authorId = 19L,
                            name = "Tasty Cotton Fish",
                            publishDate = new DateTime(2023, 3, 26, 0, 3, 24, 697, DateTimeKind.Local).AddTicks(5549)
                        },
                        new
                        {
                            id = 67L,
                            authorId = 9L,
                            name = "Sleek Soft Shoes",
                            publishDate = new DateTime(2023, 11, 4, 6, 40, 13, 559, DateTimeKind.Local).AddTicks(3350)
                        },
                        new
                        {
                            id = 68L,
                            authorId = 10L,
                            name = "Licensed Steel Tuna",
                            publishDate = new DateTime(2022, 11, 22, 10, 52, 15, 224, DateTimeKind.Local).AddTicks(8188)
                        },
                        new
                        {
                            id = 69L,
                            authorId = 21L,
                            name = "Handcrafted Granite Cheese",
                            publishDate = new DateTime(2023, 8, 8, 16, 40, 13, 216, DateTimeKind.Local).AddTicks(6767)
                        },
                        new
                        {
                            id = 70L,
                            authorId = 14L,
                            name = "Practical Steel Soap",
                            publishDate = new DateTime(2023, 10, 18, 13, 46, 4, 365, DateTimeKind.Local).AddTicks(4)
                        },
                        new
                        {
                            id = 71L,
                            authorId = 3L,
                            name = "Refined Rubber Cheese",
                            publishDate = new DateTime(2023, 5, 8, 22, 41, 38, 715, DateTimeKind.Local).AddTicks(8046)
                        },
                        new
                        {
                            id = 72L,
                            authorId = 18L,
                            name = "Unbranded Granite Keyboard",
                            publishDate = new DateTime(2022, 11, 19, 13, 56, 3, 943, DateTimeKind.Local).AddTicks(9695)
                        },
                        new
                        {
                            id = 73L,
                            authorId = 11L,
                            name = "Tasty Cotton Hat",
                            publishDate = new DateTime(2023, 3, 10, 4, 43, 46, 920, DateTimeKind.Local).AddTicks(4342)
                        },
                        new
                        {
                            id = 74L,
                            authorId = 14L,
                            name = "Refined Granite Shirt",
                            publishDate = new DateTime(2023, 7, 11, 7, 24, 29, 132, DateTimeKind.Local).AddTicks(314)
                        },
                        new
                        {
                            id = 75L,
                            authorId = 4L,
                            name = "Unbranded Rubber Chips",
                            publishDate = new DateTime(2022, 12, 22, 11, 36, 25, 572, DateTimeKind.Local).AddTicks(5589)
                        },
                        new
                        {
                            id = 76L,
                            authorId = 10L,
                            name = "Fantastic Cotton Chair",
                            publishDate = new DateTime(2022, 11, 24, 14, 52, 5, 858, DateTimeKind.Local).AddTicks(3533)
                        },
                        new
                        {
                            id = 77L,
                            authorId = 10L,
                            name = "Fantastic Wooden Towels",
                            publishDate = new DateTime(2022, 12, 2, 20, 16, 15, 711, DateTimeKind.Local).AddTicks(7890)
                        },
                        new
                        {
                            id = 78L,
                            authorId = 12L,
                            name = "Rustic Plastic Chicken",
                            publishDate = new DateTime(2023, 10, 8, 23, 18, 10, 59, DateTimeKind.Local).AddTicks(5565)
                        },
                        new
                        {
                            id = 79L,
                            authorId = 25L,
                            name = "Rustic Plastic Computer",
                            publishDate = new DateTime(2023, 6, 19, 23, 43, 39, 106, DateTimeKind.Local).AddTicks(2645)
                        },
                        new
                        {
                            id = 80L,
                            authorId = 4L,
                            name = "Handcrafted Concrete Fish",
                            publishDate = new DateTime(2022, 11, 13, 23, 52, 3, 441, DateTimeKind.Local).AddTicks(7370)
                        },
                        new
                        {
                            id = 81L,
                            authorId = 13L,
                            name = "Handcrafted Granite Car",
                            publishDate = new DateTime(2023, 6, 25, 19, 24, 35, 711, DateTimeKind.Local).AddTicks(5155)
                        },
                        new
                        {
                            id = 82L,
                            authorId = 24L,
                            name = "Awesome Frozen Computer",
                            publishDate = new DateTime(2023, 8, 21, 6, 8, 10, 958, DateTimeKind.Local).AddTicks(6523)
                        },
                        new
                        {
                            id = 83L,
                            authorId = 15L,
                            name = "Rustic Cotton Pants",
                            publishDate = new DateTime(2022, 12, 19, 0, 48, 46, 236, DateTimeKind.Local).AddTicks(16)
                        },
                        new
                        {
                            id = 84L,
                            authorId = 12L,
                            name = "Small Metal Chicken",
                            publishDate = new DateTime(2023, 6, 7, 0, 39, 28, 290, DateTimeKind.Local).AddTicks(7295)
                        },
                        new
                        {
                            id = 85L,
                            authorId = 8L,
                            name = "Awesome Soft Computer",
                            publishDate = new DateTime(2023, 1, 23, 21, 37, 21, 151, DateTimeKind.Local).AddTicks(7661)
                        },
                        new
                        {
                            id = 86L,
                            authorId = 18L,
                            name = "Unbranded Concrete Pizza",
                            publishDate = new DateTime(2023, 4, 1, 19, 33, 13, 15, DateTimeKind.Local).AddTicks(9014)
                        },
                        new
                        {
                            id = 87L,
                            authorId = 8L,
                            name = "Handmade Cotton Towels",
                            publishDate = new DateTime(2023, 5, 5, 18, 30, 32, 213, DateTimeKind.Local).AddTicks(2065)
                        },
                        new
                        {
                            id = 88L,
                            authorId = 20L,
                            name = "Fantastic Steel Chicken",
                            publishDate = new DateTime(2023, 3, 6, 2, 26, 44, 286, DateTimeKind.Local).AddTicks(2479)
                        },
                        new
                        {
                            id = 89L,
                            authorId = 17L,
                            name = "Refined Frozen Bike",
                            publishDate = new DateTime(2022, 12, 28, 4, 46, 50, 51, DateTimeKind.Local).AddTicks(8050)
                        },
                        new
                        {
                            id = 90L,
                            authorId = 13L,
                            name = "Incredible Metal Shirt",
                            publishDate = new DateTime(2023, 6, 9, 1, 27, 27, 146, DateTimeKind.Local).AddTicks(6225)
                        },
                        new
                        {
                            id = 91L,
                            authorId = 22L,
                            name = "Small Plastic Bacon",
                            publishDate = new DateTime(2023, 2, 27, 19, 17, 2, 665, DateTimeKind.Local).AddTicks(3505)
                        },
                        new
                        {
                            id = 92L,
                            authorId = 5L,
                            name = "Tasty Soft Car",
                            publishDate = new DateTime(2023, 6, 7, 19, 49, 18, 247, DateTimeKind.Local).AddTicks(2908)
                        },
                        new
                        {
                            id = 93L,
                            authorId = 21L,
                            name = "Generic Metal Bacon",
                            publishDate = new DateTime(2022, 12, 31, 16, 3, 46, 415, DateTimeKind.Local).AddTicks(8760)
                        },
                        new
                        {
                            id = 94L,
                            authorId = 23L,
                            name = "Rustic Frozen Car",
                            publishDate = new DateTime(2023, 5, 19, 3, 5, 8, 843, DateTimeKind.Local).AddTicks(9480)
                        },
                        new
                        {
                            id = 95L,
                            authorId = 9L,
                            name = "Generic Granite Tuna",
                            publishDate = new DateTime(2023, 9, 22, 13, 48, 5, 118, DateTimeKind.Local).AddTicks(6630)
                        },
                        new
                        {
                            id = 96L,
                            authorId = 23L,
                            name = "Practical Rubber Pizza",
                            publishDate = new DateTime(2023, 10, 1, 2, 16, 56, 63, DateTimeKind.Local).AddTicks(2304)
                        },
                        new
                        {
                            id = 97L,
                            authorId = 18L,
                            name = "Handmade Metal Car",
                            publishDate = new DateTime(2023, 10, 17, 5, 26, 9, 631, DateTimeKind.Local).AddTicks(6292)
                        },
                        new
                        {
                            id = 98L,
                            authorId = 12L,
                            name = "Sleek Fresh Car",
                            publishDate = new DateTime(2022, 12, 7, 7, 35, 9, 882, DateTimeKind.Local).AddTicks(674)
                        },
                        new
                        {
                            id = 99L,
                            authorId = 23L,
                            name = "Fantastic Metal Bacon",
                            publishDate = new DateTime(2023, 4, 13, 17, 51, 30, 785, DateTimeKind.Local).AddTicks(1414)
                        },
                        new
                        {
                            id = 100L,
                            authorId = 26L,
                            name = "Fantastic Wooden Tuna",
                            publishDate = new DateTime(2022, 11, 19, 20, 54, 43, 165, DateTimeKind.Local).AddTicks(746)
                        },
                        new
                        {
                            id = 101L,
                            authorId = 20L,
                            name = "Fantastic Wooden Pizza",
                            publishDate = new DateTime(2023, 2, 27, 2, 4, 35, 254, DateTimeKind.Local).AddTicks(2227)
                        },
                        new
                        {
                            id = 102L,
                            authorId = 22L,
                            name = "Intelligent Fresh Towels",
                            publishDate = new DateTime(2022, 12, 11, 6, 48, 57, 977, DateTimeKind.Local).AddTicks(527)
                        },
                        new
                        {
                            id = 103L,
                            authorId = 16L,
                            name = "Unbranded Soft Bike",
                            publishDate = new DateTime(2022, 12, 22, 19, 16, 49, 865, DateTimeKind.Local).AddTicks(1709)
                        },
                        new
                        {
                            id = 104L,
                            authorId = 22L,
                            name = "Small Concrete Chips",
                            publishDate = new DateTime(2023, 6, 11, 7, 30, 51, 682, DateTimeKind.Local).AddTicks(2326)
                        },
                        new
                        {
                            id = 105L,
                            authorId = 25L,
                            name = "Sleek Metal Chips",
                            publishDate = new DateTime(2023, 7, 18, 14, 6, 43, 792, DateTimeKind.Local).AddTicks(6406)
                        },
                        new
                        {
                            id = 106L,
                            authorId = 21L,
                            name = "Handmade Frozen Sausages",
                            publishDate = new DateTime(2023, 1, 16, 13, 7, 0, 41, DateTimeKind.Local).AddTicks(474)
                        },
                        new
                        {
                            id = 107L,
                            authorId = 3L,
                            name = "Generic Fresh Shoes",
                            publishDate = new DateTime(2023, 6, 2, 8, 16, 15, 570, DateTimeKind.Local).AddTicks(203)
                        },
                        new
                        {
                            id = 108L,
                            authorId = 27L,
                            name = "Rustic Granite Computer",
                            publishDate = new DateTime(2023, 5, 15, 15, 6, 41, 682, DateTimeKind.Local).AddTicks(3264)
                        },
                        new
                        {
                            id = 109L,
                            authorId = 9L,
                            name = "Refined Metal Cheese",
                            publishDate = new DateTime(2023, 7, 20, 4, 34, 21, 749, DateTimeKind.Local).AddTicks(6198)
                        },
                        new
                        {
                            id = 110L,
                            authorId = 6L,
                            name = "Handmade Wooden Sausages",
                            publishDate = new DateTime(2022, 12, 14, 1, 35, 29, 990, DateTimeKind.Local).AddTicks(7274)
                        },
                        new
                        {
                            id = 111L,
                            authorId = 14L,
                            name = "Ergonomic Wooden Mouse",
                            publishDate = new DateTime(2023, 2, 12, 22, 13, 35, 3, DateTimeKind.Local).AddTicks(6499)
                        },
                        new
                        {
                            id = 112L,
                            authorId = 27L,
                            name = "Generic Concrete Sausages",
                            publishDate = new DateTime(2023, 10, 1, 4, 37, 33, 193, DateTimeKind.Local).AddTicks(3271)
                        },
                        new
                        {
                            id = 113L,
                            authorId = 11L,
                            name = "Handcrafted Cotton Computer",
                            publishDate = new DateTime(2023, 3, 10, 19, 47, 31, 205, DateTimeKind.Local).AddTicks(6008)
                        },
                        new
                        {
                            id = 114L,
                            authorId = 6L,
                            name = "Intelligent Plastic Ball",
                            publishDate = new DateTime(2023, 6, 20, 23, 21, 46, 569, DateTimeKind.Local).AddTicks(6365)
                        },
                        new
                        {
                            id = 115L,
                            authorId = 8L,
                            name = "Rustic Steel Computer",
                            publishDate = new DateTime(2023, 7, 30, 20, 15, 22, 656, DateTimeKind.Local).AddTicks(6483)
                        },
                        new
                        {
                            id = 116L,
                            authorId = 16L,
                            name = "Incredible Wooden Cheese",
                            publishDate = new DateTime(2023, 6, 17, 12, 12, 16, 235, DateTimeKind.Local).AddTicks(9488)
                        },
                        new
                        {
                            id = 117L,
                            authorId = 2L,
                            name = "Generic Soft Car",
                            publishDate = new DateTime(2023, 7, 3, 7, 58, 54, 630, DateTimeKind.Local).AddTicks(7295)
                        },
                        new
                        {
                            id = 118L,
                            authorId = 9L,
                            name = "Sleek Metal Fish",
                            publishDate = new DateTime(2023, 7, 8, 21, 44, 39, 169, DateTimeKind.Local).AddTicks(7070)
                        },
                        new
                        {
                            id = 119L,
                            authorId = 10L,
                            name = "Licensed Steel Bike",
                            publishDate = new DateTime(2023, 4, 12, 14, 19, 56, 164, DateTimeKind.Local).AddTicks(9196)
                        },
                        new
                        {
                            id = 120L,
                            authorId = 26L,
                            name = "Licensed Concrete Bike",
                            publishDate = new DateTime(2023, 6, 19, 7, 11, 4, 484, DateTimeKind.Local).AddTicks(4836)
                        },
                        new
                        {
                            id = 121L,
                            authorId = 4L,
                            name = "Tasty Cotton Cheese",
                            publishDate = new DateTime(2023, 2, 9, 5, 47, 48, 899, DateTimeKind.Local).AddTicks(4291)
                        },
                        new
                        {
                            id = 122L,
                            authorId = 23L,
                            name = "Fantastic Cotton Gloves",
                            publishDate = new DateTime(2023, 5, 7, 1, 56, 42, 452, DateTimeKind.Local).AddTicks(4483)
                        },
                        new
                        {
                            id = 123L,
                            authorId = 11L,
                            name = "Fantastic Cotton Keyboard",
                            publishDate = new DateTime(2023, 3, 17, 5, 59, 54, 59, DateTimeKind.Local).AddTicks(9741)
                        },
                        new
                        {
                            id = 124L,
                            authorId = 19L,
                            name = "Small Metal Towels",
                            publishDate = new DateTime(2022, 11, 19, 21, 40, 57, 722, DateTimeKind.Local).AddTicks(8051)
                        },
                        new
                        {
                            id = 125L,
                            authorId = 22L,
                            name = "Incredible Soft Computer",
                            publishDate = new DateTime(2023, 1, 2, 5, 17, 42, 514, DateTimeKind.Local).AddTicks(7906)
                        },
                        new
                        {
                            id = 126L,
                            authorId = 22L,
                            name = "Rustic Rubber Soap",
                            publishDate = new DateTime(2023, 11, 10, 5, 53, 53, 38, DateTimeKind.Local).AddTicks(9691)
                        },
                        new
                        {
                            id = 127L,
                            authorId = 27L,
                            name = "Handcrafted Soft Salad",
                            publishDate = new DateTime(2023, 9, 27, 19, 37, 44, 505, DateTimeKind.Local).AddTicks(8581)
                        },
                        new
                        {
                            id = 128L,
                            authorId = 28L,
                            name = "Ergonomic Metal Soap",
                            publishDate = new DateTime(2022, 11, 25, 14, 31, 12, 752, DateTimeKind.Local).AddTicks(3404)
                        },
                        new
                        {
                            id = 129L,
                            authorId = 1L,
                            name = "Refined Metal Gloves",
                            publishDate = new DateTime(2022, 11, 20, 10, 19, 2, 394, DateTimeKind.Local).AddTicks(2503)
                        },
                        new
                        {
                            id = 130L,
                            authorId = 25L,
                            name = "Fantastic Steel Chair",
                            publishDate = new DateTime(2023, 9, 4, 12, 16, 34, 202, DateTimeKind.Local).AddTicks(4758)
                        },
                        new
                        {
                            id = 131L,
                            authorId = 6L,
                            name = "Practical Granite Chips",
                            publishDate = new DateTime(2023, 9, 24, 0, 39, 46, 549, DateTimeKind.Local).AddTicks(1207)
                        },
                        new
                        {
                            id = 132L,
                            authorId = 21L,
                            name = "Awesome Steel Gloves",
                            publishDate = new DateTime(2023, 9, 26, 19, 46, 44, 547, DateTimeKind.Local).AddTicks(8799)
                        },
                        new
                        {
                            id = 133L,
                            authorId = 6L,
                            name = "Sleek Concrete Bike",
                            publishDate = new DateTime(2023, 10, 28, 7, 49, 10, 877, DateTimeKind.Local).AddTicks(5852)
                        },
                        new
                        {
                            id = 134L,
                            authorId = 15L,
                            name = "Ergonomic Cotton Ball",
                            publishDate = new DateTime(2023, 6, 11, 12, 8, 43, 332, DateTimeKind.Local).AddTicks(1751)
                        },
                        new
                        {
                            id = 135L,
                            authorId = 28L,
                            name = "Handmade Soft Computer",
                            publishDate = new DateTime(2023, 3, 17, 17, 33, 21, 44, DateTimeKind.Local).AddTicks(1601)
                        },
                        new
                        {
                            id = 136L,
                            authorId = 11L,
                            name = "Awesome Concrete Table",
                            publishDate = new DateTime(2023, 2, 22, 5, 19, 15, 61, DateTimeKind.Local).AddTicks(8061)
                        },
                        new
                        {
                            id = 137L,
                            authorId = 11L,
                            name = "Licensed Concrete Bacon",
                            publishDate = new DateTime(2023, 7, 20, 16, 37, 46, 703, DateTimeKind.Local).AddTicks(3668)
                        },
                        new
                        {
                            id = 138L,
                            authorId = 22L,
                            name = "Incredible Rubber Soap",
                            publishDate = new DateTime(2023, 7, 21, 1, 20, 18, 102, DateTimeKind.Local).AddTicks(2357)
                        },
                        new
                        {
                            id = 139L,
                            authorId = 22L,
                            name = "Licensed Frozen Table",
                            publishDate = new DateTime(2023, 4, 7, 9, 1, 27, 600, DateTimeKind.Local).AddTicks(1281)
                        },
                        new
                        {
                            id = 140L,
                            authorId = 23L,
                            name = "Generic Granite Shoes",
                            publishDate = new DateTime(2023, 4, 2, 14, 9, 20, 159, DateTimeKind.Local).AddTicks(5686)
                        },
                        new
                        {
                            id = 141L,
                            authorId = 6L,
                            name = "Practical Soft Tuna",
                            publishDate = new DateTime(2023, 1, 4, 21, 54, 35, 378, DateTimeKind.Local).AddTicks(7594)
                        },
                        new
                        {
                            id = 142L,
                            authorId = 4L,
                            name = "Practical Rubber Salad",
                            publishDate = new DateTime(2023, 5, 25, 9, 13, 53, 54, DateTimeKind.Local).AddTicks(1077)
                        },
                        new
                        {
                            id = 143L,
                            authorId = 9L,
                            name = "Practical Fresh Bike",
                            publishDate = new DateTime(2023, 4, 6, 0, 17, 43, 992, DateTimeKind.Local).AddTicks(3311)
                        },
                        new
                        {
                            id = 144L,
                            authorId = 12L,
                            name = "Tasty Plastic Tuna",
                            publishDate = new DateTime(2023, 8, 18, 5, 42, 40, 1, DateTimeKind.Local).AddTicks(3404)
                        },
                        new
                        {
                            id = 145L,
                            authorId = 6L,
                            name = "Ergonomic Concrete Pants",
                            publishDate = new DateTime(2023, 7, 6, 13, 41, 28, 307, DateTimeKind.Local).AddTicks(488)
                        },
                        new
                        {
                            id = 146L,
                            authorId = 16L,
                            name = "Intelligent Steel Cheese",
                            publishDate = new DateTime(2022, 12, 19, 4, 38, 11, 955, DateTimeKind.Local).AddTicks(4956)
                        },
                        new
                        {
                            id = 147L,
                            authorId = 24L,
                            name = "Generic Frozen Ball",
                            publishDate = new DateTime(2023, 9, 17, 7, 23, 13, 89, DateTimeKind.Local).AddTicks(9292)
                        },
                        new
                        {
                            id = 148L,
                            authorId = 11L,
                            name = "Unbranded Metal Bacon",
                            publishDate = new DateTime(2023, 7, 31, 23, 13, 57, 829, DateTimeKind.Local).AddTicks(655)
                        },
                        new
                        {
                            id = 149L,
                            authorId = 20L,
                            name = "Gorgeous Granite Bike",
                            publishDate = new DateTime(2023, 2, 8, 14, 55, 48, 118, DateTimeKind.Local).AddTicks(5557)
                        },
                        new
                        {
                            id = 150L,
                            authorId = 7L,
                            name = "Awesome Rubber Ball",
                            publishDate = new DateTime(2023, 8, 16, 19, 29, 42, 17, DateTimeKind.Local).AddTicks(2364)
                        },
                        new
                        {
                            id = 151L,
                            authorId = 1L,
                            name = "Incredible Plastic Pizza",
                            publishDate = new DateTime(2023, 5, 29, 9, 16, 35, 128, DateTimeKind.Local).AddTicks(1615)
                        },
                        new
                        {
                            id = 152L,
                            authorId = 20L,
                            name = "Fantastic Steel Pants",
                            publishDate = new DateTime(2023, 6, 10, 17, 41, 45, 264, DateTimeKind.Local).AddTicks(3572)
                        },
                        new
                        {
                            id = 153L,
                            authorId = 11L,
                            name = "Gorgeous Concrete Shoes",
                            publishDate = new DateTime(2023, 7, 8, 19, 40, 42, 975, DateTimeKind.Local).AddTicks(7620)
                        },
                        new
                        {
                            id = 154L,
                            authorId = 16L,
                            name = "Rustic Wooden Shirt",
                            publishDate = new DateTime(2023, 6, 8, 4, 40, 0, 686, DateTimeKind.Local).AddTicks(4893)
                        },
                        new
                        {
                            id = 155L,
                            authorId = 6L,
                            name = "Tasty Soft Bike",
                            publishDate = new DateTime(2023, 5, 9, 8, 10, 23, 468, DateTimeKind.Local).AddTicks(3626)
                        },
                        new
                        {
                            id = 156L,
                            authorId = 13L,
                            name = "Gorgeous Metal Hat",
                            publishDate = new DateTime(2023, 1, 26, 13, 9, 7, 722, DateTimeKind.Local).AddTicks(260)
                        },
                        new
                        {
                            id = 157L,
                            authorId = 25L,
                            name = "Small Frozen Gloves",
                            publishDate = new DateTime(2023, 5, 25, 5, 39, 6, 296, DateTimeKind.Local).AddTicks(4347)
                        },
                        new
                        {
                            id = 158L,
                            authorId = 9L,
                            name = "Rustic Fresh Chicken",
                            publishDate = new DateTime(2023, 4, 26, 9, 20, 50, 748, DateTimeKind.Local).AddTicks(366)
                        },
                        new
                        {
                            id = 159L,
                            authorId = 1L,
                            name = "Tasty Wooden Car",
                            publishDate = new DateTime(2022, 12, 28, 20, 23, 56, 693, DateTimeKind.Local).AddTicks(7126)
                        },
                        new
                        {
                            id = 160L,
                            authorId = 2L,
                            name = "Rustic Plastic Hat",
                            publishDate = new DateTime(2023, 4, 3, 17, 47, 5, 505, DateTimeKind.Local).AddTicks(869)
                        },
                        new
                        {
                            id = 161L,
                            authorId = 22L,
                            name = "Awesome Fresh Pizza",
                            publishDate = new DateTime(2023, 2, 18, 7, 26, 23, 136, DateTimeKind.Local).AddTicks(6879)
                        },
                        new
                        {
                            id = 162L,
                            authorId = 21L,
                            name = "Intelligent Granite Keyboard",
                            publishDate = new DateTime(2023, 9, 10, 21, 15, 4, 933, DateTimeKind.Local).AddTicks(8874)
                        },
                        new
                        {
                            id = 163L,
                            authorId = 29L,
                            name = "Ergonomic Soft Cheese",
                            publishDate = new DateTime(2023, 1, 16, 7, 15, 42, 833, DateTimeKind.Local).AddTicks(6268)
                        },
                        new
                        {
                            id = 164L,
                            authorId = 18L,
                            name = "Incredible Soft Chips",
                            publishDate = new DateTime(2023, 4, 12, 20, 42, 0, 375, DateTimeKind.Local).AddTicks(6345)
                        },
                        new
                        {
                            id = 165L,
                            authorId = 1L,
                            name = "Licensed Steel Shirt",
                            publishDate = new DateTime(2023, 6, 5, 5, 50, 7, 180, DateTimeKind.Local).AddTicks(7363)
                        },
                        new
                        {
                            id = 166L,
                            authorId = 15L,
                            name = "Handcrafted Fresh Gloves",
                            publishDate = new DateTime(2023, 6, 24, 6, 54, 47, 540, DateTimeKind.Local).AddTicks(9845)
                        },
                        new
                        {
                            id = 167L,
                            authorId = 11L,
                            name = "Sleek Frozen Shirt",
                            publishDate = new DateTime(2023, 11, 5, 8, 51, 17, 811, DateTimeKind.Local).AddTicks(7489)
                        },
                        new
                        {
                            id = 168L,
                            authorId = 9L,
                            name = "Ergonomic Granite Ball",
                            publishDate = new DateTime(2023, 3, 14, 18, 47, 37, 596, DateTimeKind.Local).AddTicks(2523)
                        },
                        new
                        {
                            id = 169L,
                            authorId = 11L,
                            name = "Intelligent Rubber Sausages",
                            publishDate = new DateTime(2023, 6, 9, 9, 37, 50, 201, DateTimeKind.Local).AddTicks(8792)
                        },
                        new
                        {
                            id = 170L,
                            authorId = 24L,
                            name = "Refined Soft Soap",
                            publishDate = new DateTime(2023, 4, 15, 5, 25, 17, 875, DateTimeKind.Local).AddTicks(6925)
                        },
                        new
                        {
                            id = 171L,
                            authorId = 12L,
                            name = "Licensed Wooden Pants",
                            publishDate = new DateTime(2023, 7, 14, 6, 23, 44, 386, DateTimeKind.Local).AddTicks(9525)
                        },
                        new
                        {
                            id = 172L,
                            authorId = 5L,
                            name = "Rustic Fresh Mouse",
                            publishDate = new DateTime(2023, 9, 2, 1, 25, 0, 876, DateTimeKind.Local).AddTicks(370)
                        },
                        new
                        {
                            id = 173L,
                            authorId = 9L,
                            name = "Rustic Granite Car",
                            publishDate = new DateTime(2023, 10, 12, 20, 12, 57, 858, DateTimeKind.Local).AddTicks(2126)
                        },
                        new
                        {
                            id = 174L,
                            authorId = 13L,
                            name = "Unbranded Steel Salad",
                            publishDate = new DateTime(2023, 3, 15, 5, 50, 13, 847, DateTimeKind.Local).AddTicks(3499)
                        },
                        new
                        {
                            id = 175L,
                            authorId = 15L,
                            name = "Awesome Granite Mouse",
                            publishDate = new DateTime(2023, 8, 13, 15, 34, 57, 859, DateTimeKind.Local).AddTicks(3640)
                        },
                        new
                        {
                            id = 176L,
                            authorId = 24L,
                            name = "Ergonomic Wooden Computer",
                            publishDate = new DateTime(2023, 4, 12, 4, 27, 6, 252, DateTimeKind.Local).AddTicks(5578)
                        },
                        new
                        {
                            id = 177L,
                            authorId = 3L,
                            name = "Sleek Wooden Soap",
                            publishDate = new DateTime(2023, 2, 19, 21, 17, 25, 613, DateTimeKind.Local).AddTicks(3449)
                        },
                        new
                        {
                            id = 178L,
                            authorId = 19L,
                            name = "Licensed Granite Fish",
                            publishDate = new DateTime(2023, 11, 6, 1, 57, 5, 773, DateTimeKind.Local).AddTicks(6762)
                        },
                        new
                        {
                            id = 179L,
                            authorId = 29L,
                            name = "Practical Fresh Tuna",
                            publishDate = new DateTime(2023, 4, 22, 1, 1, 20, 972, DateTimeKind.Local).AddTicks(3058)
                        },
                        new
                        {
                            id = 180L,
                            authorId = 15L,
                            name = "Sleek Frozen Ball",
                            publishDate = new DateTime(2023, 3, 13, 16, 2, 53, 879, DateTimeKind.Local).AddTicks(2924)
                        },
                        new
                        {
                            id = 181L,
                            authorId = 20L,
                            name = "Handmade Concrete Pizza",
                            publishDate = new DateTime(2023, 4, 1, 8, 51, 25, 130, DateTimeKind.Local).AddTicks(2253)
                        },
                        new
                        {
                            id = 182L,
                            authorId = 3L,
                            name = "Practical Concrete Fish",
                            publishDate = new DateTime(2023, 9, 26, 13, 13, 50, 874, DateTimeKind.Local).AddTicks(4046)
                        },
                        new
                        {
                            id = 183L,
                            authorId = 22L,
                            name = "Handmade Plastic Pizza",
                            publishDate = new DateTime(2023, 6, 30, 7, 34, 45, 14, DateTimeKind.Local).AddTicks(1649)
                        },
                        new
                        {
                            id = 184L,
                            authorId = 18L,
                            name = "Generic Plastic Shoes",
                            publishDate = new DateTime(2023, 3, 20, 11, 18, 42, 342, DateTimeKind.Local).AddTicks(3747)
                        },
                        new
                        {
                            id = 185L,
                            authorId = 23L,
                            name = "Small Soft Bacon",
                            publishDate = new DateTime(2023, 10, 31, 4, 34, 39, 450, DateTimeKind.Local).AddTicks(7260)
                        },
                        new
                        {
                            id = 186L,
                            authorId = 29L,
                            name = "Gorgeous Granite Pants",
                            publishDate = new DateTime(2023, 4, 2, 19, 57, 31, 277, DateTimeKind.Local).AddTicks(7125)
                        },
                        new
                        {
                            id = 187L,
                            authorId = 2L,
                            name = "Handmade Steel Tuna",
                            publishDate = new DateTime(2023, 10, 1, 21, 32, 54, 469, DateTimeKind.Local).AddTicks(37)
                        },
                        new
                        {
                            id = 188L,
                            authorId = 5L,
                            name = "Practical Plastic Keyboard",
                            publishDate = new DateTime(2023, 4, 12, 16, 52, 15, 565, DateTimeKind.Local).AddTicks(7243)
                        },
                        new
                        {
                            id = 189L,
                            authorId = 15L,
                            name = "Intelligent Granite Hat",
                            publishDate = new DateTime(2022, 12, 11, 23, 48, 7, 371, DateTimeKind.Local).AddTicks(136)
                        },
                        new
                        {
                            id = 190L,
                            authorId = 13L,
                            name = "Gorgeous Granite Computer",
                            publishDate = new DateTime(2023, 7, 21, 1, 52, 43, 950, DateTimeKind.Local).AddTicks(7836)
                        },
                        new
                        {
                            id = 191L,
                            authorId = 14L,
                            name = "Fantastic Granite Chair",
                            publishDate = new DateTime(2023, 5, 1, 2, 21, 40, 244, DateTimeKind.Local).AddTicks(8086)
                        },
                        new
                        {
                            id = 192L,
                            authorId = 18L,
                            name = "Handcrafted Plastic Shirt",
                            publishDate = new DateTime(2023, 10, 9, 9, 32, 58, 444, DateTimeKind.Local).AddTicks(1482)
                        },
                        new
                        {
                            id = 193L,
                            authorId = 15L,
                            name = "Incredible Steel Hat",
                            publishDate = new DateTime(2023, 2, 13, 14, 56, 46, 386, DateTimeKind.Local).AddTicks(955)
                        },
                        new
                        {
                            id = 194L,
                            authorId = 5L,
                            name = "Rustic Concrete Shirt",
                            publishDate = new DateTime(2023, 8, 9, 20, 8, 27, 987, DateTimeKind.Local).AddTicks(7858)
                        },
                        new
                        {
                            id = 195L,
                            authorId = 29L,
                            name = "Licensed Concrete Salad",
                            publishDate = new DateTime(2023, 6, 8, 0, 43, 59, 453, DateTimeKind.Local).AddTicks(5897)
                        },
                        new
                        {
                            id = 196L,
                            authorId = 23L,
                            name = "Awesome Rubber Chicken",
                            publishDate = new DateTime(2023, 7, 1, 3, 16, 28, 27, DateTimeKind.Local).AddTicks(3531)
                        },
                        new
                        {
                            id = 197L,
                            authorId = 17L,
                            name = "Rustic Plastic Keyboard",
                            publishDate = new DateTime(2023, 10, 21, 4, 1, 3, 90, DateTimeKind.Local).AddTicks(5374)
                        },
                        new
                        {
                            id = 198L,
                            authorId = 20L,
                            name = "Refined Rubber Shirt",
                            publishDate = new DateTime(2023, 4, 17, 8, 0, 51, 799, DateTimeKind.Local).AddTicks(8275)
                        },
                        new
                        {
                            id = 199L,
                            authorId = 8L,
                            name = "Handcrafted Granite Tuna",
                            publishDate = new DateTime(2023, 2, 3, 21, 0, 0, 893, DateTimeKind.Local).AddTicks(1335)
                        },
                        new
                        {
                            id = 200L,
                            authorId = 5L,
                            name = "Practical Fresh Sausages",
                            publishDate = new DateTime(2023, 6, 29, 10, 50, 46, 950, DateTimeKind.Local).AddTicks(895)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
