name: beer_me
description: A mobile app allowing You to scan Your beer and get information about it!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  intl: any

  cupertino_icons: ^1.0.2
  openid_client: ^0.4.8
  url_launcher: ^6.2.1
  flutter_floating_bottom_bar: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  analyzer: ^5.12.0

  flutter_lints: ^3.0.0

flutter:
  generate: true # localization translation generator

  uses-material-design: true

  assets:
     - lib/assets/
     - lib/assets/images/default_fallbacks/unknown_beer.png
     - lib/assets/images/default_fallbacks/unknown_brewery.png
  fonts:
    - family: Raleway
      fonts:
      - asset: assets/fonts/Raleway/Raleway-Regular.ttf
      - asset: assets/fonts/Raleway/Raleway-Italic.ttf
        style: italic
